### ISSUE TITLE
add members to the IRB team

### ISSUE THREAD

**Issue by robinjonesphd** [vanderbilt-stuttering-lab/IRB#1]

**Comment by robinjonesphd** [comment]
Invited Aysu to join the vanderbilt-stuttering-lab organization

**Comment by robinjonesphd** [comment]
Aysu, are you added to the IRB repository?

**Comment by robinjonesphd** [comment]
Or do you only see the issue: "add members to the IRB team"?

**Comment by robinjonesphd** [comment]
Aysu, can you see the project: "REDCap consent/assent"?

**Comment by erdemiraysu** [comment]
Hi Robin,

Yes I can see all 3 issues and I can see the project. Is there a way to
communicate with you over there? Trying to figure out how you sent me this
email.
So would you expect me to attach the RedCap pdf's in there and resolve the
issues?

Aysu
